### ISSUE TITLE
Admin address and risks of private key disclosure and centralized administration without road to decentralization 

### ISSUE THREAD

**Issue by alerdenisov** [WhiteMatrixTech/cell-evolution-all#39]
Guys, found your project as recently indexed on github. Your project looks delicious, I love solidity based games. 

Do you host it somewhere to play with you?

I afraid about this line of code: https://github.com/WhiteMatrixTech/cell-evolution-all/blob/c6d7441366eb14f7587587f4f25eb2d7c5e998c1/packages/cell-evolution-contracts/contracts/CellEvolutionNewWorld.sol#L14 
1) Looks like owner can not be changed in the future accordingly lack of `transferOwnership` method. (I suggest to take a look on `Ownable` pattern from [openzeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol))
2) What is your plan about admin's private key? How do you protect users from disclosure or unauthorized behaviour (such as FTX)?

**Comment by wufengtao1** [comment]
Sorry for taking so long to reply to your question.

1. That's indeed a good idea, and we can set the owner to the zero address later on.
2. A multi-signature wallet could be a good option. Time flies, and it's already been six months since FTX.
